version: '3.1'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: location_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  location_api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: .env.docker
    restart: always
    container_name: location_api
    ports:
      - "3001:3001"
    depends_on:
      - postgres_db

volumes:
  postgres_data:
